---
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: nuclei
  commands:
  - go get -v -u github.com/xm1k3/cent
  - go get -v -u github.com/projectdiscovery/dnsx/cmd/dnsx
  - go get -v -u github.com/projectdiscovery/httpx/cmd/httpx
  - go get -v -u github.com/projectdiscovery/nuclei/v2/cmd/nuclei
  - go get -v -u github.com/projectdiscovery/naabu/v2/cmd/naabu
  - cent init
  - cent -p ~/nuclei-templates -k -C -t 100
  - nuclei -u http://127.0.0.1 -impact critical,high,medium
  environment:
    GO111MODULE: on
    
trigger:
  branch:
  - main
